"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.rolePriorities = void 0;
const rolePriorities = function () {
    const priorities = {};
    priorities["ferry" /* FERRY_NAME */] = 0;
    priorities["defender" /* DEFENDER_NAME */] = 2;
    priorities["transporter" /* TRANSPORTER_NAME */] = 1;
    priorities["remoteMiner" /* REMOTE_MINER_NAME */] = 3;
    priorities["skGuard" /* SK_GUARD_NAME */] = 3;
    priorities["runner" /* RUNNER_NAME */] = 2;
    priorities["upgrader" /* UPGRADER_NAME */] = 5;
    priorities["builder" /* BUILDER_NAME */] = 6;
    priorities["quad" /* QUAD_NAME */] = 3;
    priorities["mineralMiner" /* MINERAL_MINER_NAME */] = 8;
    priorities["claimer" /* CLAIMER_NAME */] = 9;
    priorities["unclaimer" /* UNCLAIMER_NAME */] = 10;
    priorities["spawnBuilder" /* SPAWN_BUILDER_NAME */] = 11;
    priorities["harasser" /* HARASSER_NAME */] = 3;
    priorities["medic" /* MEDIC_NAME */] = 13;
    priorities["breaker" /* BREAKER_NAME */] = 13;
    priorities["powerMiner" /* POWER_MINER_NAME */] = 13;
    priorities["robber" /* ROBBER_NAME */] = 14;
    priorities["depositMiner" /* DEPOSIT_MINER_NAME */] = 15;
    priorities["scout" /* SCOUT_NAME */] = 16;
    priorities["qrCode" /* QR_CODE_NAME */] = 17;
    priorities["repairer" /* REPAIRER_NAME */] = 14;
    priorities["reserver" /* RESERVER_NAME */] = 15;
    priorities["brick" /* BRICK_NAME */] = 15;
    return priorities;
};
exports.rolePriorities = rolePriorities;
